
server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: root123
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000